// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsARtOG_hc33qA_KpeaR2kvnWvrWoOuC0',
    appId: '1:649581495362:web:075e3c618b88871523d9db',
    messagingSenderId: '649581495362',
    projectId: 'drive-monitoring-3e2f9',
    authDomain: 'drive-monitoring-3e2f9.firebaseapp.com',
    storageBucket: 'drive-monitoring-3e2f9.firebasestorage.app',
    measurementId: 'G-SK76CVD7Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1LDeJWPXh7ZMz15m3-w_NgAXaQsK0-8',
    appId: '1:649581495362:android:a05e5d1ddcde4e6a23d9db',
    messagingSenderId: '649581495362',
    projectId: 'drive-monitoring-3e2f9',
    storageBucket: 'drive-monitoring-3e2f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpYq87a9Z3m0w5fNrdlSIXIM-B8flYNU',
    appId: '1:649581495362:ios:2f23a045fbf9323723d9db',
    messagingSenderId: '649581495362',
    projectId: 'drive-monitoring-3e2f9',
    storageBucket: 'drive-monitoring-3e2f9.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQpYq87a9Z3m0w5fNrdlSIXIM-B8flYNU',
    appId: '1:649581495362:ios:2f23a045fbf9323723d9db',
    messagingSenderId: '649581495362',
    projectId: 'drive-monitoring-3e2f9',
    storageBucket: 'drive-monitoring-3e2f9.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsARtOG_hc33qA_KpeaR2kvnWvrWoOuC0',
    appId: '1:649581495362:web:436e3714c460fbb523d9db',
    messagingSenderId: '649581495362',
    projectId: 'drive-monitoring-3e2f9',
    authDomain: 'drive-monitoring-3e2f9.firebaseapp.com',
    storageBucket: 'drive-monitoring-3e2f9.firebasestorage.app',
    measurementId: 'G-CV6JPY1DE6',
  );
}
